language: android
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11
env:
  global:
    - GRADLE_OPTS="-Xmx1024m"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-22
    - android-27
    - sys-img-armeabi-v7a-android-22

before_script:
  - if [ "$TRAVIS_JDK_VERSION" = "oraclejdk8" ]; then
      mkdir -p $ANDROID_HOME/licenses
      echo 8933bad161af4178b1185d1a37fbf41ea5269c55 >> $ANDROID_HOME/licenses/android-sdk-license
      echo d56f5187479451eabf01fb78af6dfcb131a6481e >> $ANDROID_HOME/licenses/android-sdk-license
      echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
      emulator -avd test -no-audio -no-window &
      android-wait-for-emulator
      adb shell input keyevent 82 &
    fi
  - if [ "$TRAVIS_JDK_VERSION" != "oraclejdk8" ]; then
      rm "$JAVA_HOME/lib/security/cacerts"
      ln -s /etc/ssl/certs/java/cacerts "$JAVA_HOME/lib/security/cacerts"
    fi

script:
  - travis_retry ./gradlew clean
  - travis_retry ./gradlew generate isGitDirty
  - travis_retry ./gradlew check
  - if [ "$TRAVIS_JDK_VERSION" = "oraclejdk8" ]; then
      travis_retry ./gradlew connectedCheck
    fi
